# This file should contain all the record creation needed to experiment with
# your app during development.
#
# The data can then be loaded with the rake db:examples (or created alongside
# the db with db:nuke_pave).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

%w(rory phil danny tiger).each do |name|
  email = "#{name}@#{name}.com"
  next if User.exists? email: email
  User.create!(email: email,
               password: '123',
               password_confirmation: nil)
end

Profile.create([
                 { given_name: 'Rory',
                   surname: 'McIlroy',
                   home_course: 'Holywood Golf Club',
                   user_id: 1 },
                 { given_name: 'Phil',
                   surname: 'Mickelson',
                   home_course: 'Butter Brook',
                   user_id: 2 },
                 { given_name: 'Danny',
                   surname: 'Noonan',
                   home_course: 'Pebble Beach',
                   user_id: 3 },
                 { given_name: 'Ty',
                   surname: 'Webb',
                   home_course: 'Bushwood Country Club',
                   user_id: 3 },
                 { given_name: 'Tiger',
                   surname: 'Woods',
                   home_course: 'Pebble Beach',
                   user_id: 4 }
               ])

Round.create([
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-01',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 90,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-02',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 73,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-03',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 69,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-04',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 66,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-05',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 68,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-05',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 69,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-07',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 90,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-14',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 83,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-16',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 84,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-20',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 67,
                 profile_id: 3 },
               { course: 'Bushwood Country Club',
                 date_played: '2016-09-21',
                 rating: 74,
                 slope: 133,
                 par: 72,
                 score: 70,
                 profile_id: 3 },
               { course: 'Butter Brook',
                 date_played: '2016-10-12',
                 rating: 72.5,
                 slope: 133,
                 par: 72,
                 score: 68,
                 profile_id: 2 },
               { course: 'Butter Brook',
                 date_played: '2016-10-03',
                 rating: 72.5,
                 slope: 133,
                 par: 72,
                 score: 65,
                 profile_id: 2 },
               { course: 'Butter Brook',
                 date_played: '2016-10-05',
                 rating: 72.5,
                 slope: 133,
                 par: 72,
                 score: 70,
                 profile_id: 1 },
               { course: 'Butter Brook',
                 date_played: '2016-10-08',
                 rating: 72.5,
                 slope: 133,
                 par: 72,
                 score: 65,
                 profile_id: 2 },
               { course: 'Butter Brook',
                 date_played: '2016-09-28',
                 rating: 72.5,
                 slope: 133,
                 par: 72,
                 score: 71,
                 profile_id: 3 },
               { course: 'Lake Tahoe Golf Course',
                 date_played: '2016-10-05',
                 rating: 71.3,
                 slope: 124,
                 par: 71,
                 score: 63,
                 profile_id: 2 }
             ])
